version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 11080:80/tcp
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PASSWORD}
    volumes:
      - ${HOME}/Data/pihole/pihole:/etc/pihole/
      - ${HOME}/Data/pihole/dnsmasq/:/etc/dnsmasq.d/
      - ${HOME}/Data/pihole/log/:/var/log/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.rule=Host(${DNS_DOMAIN})"
      # - "traefik.http.routers.pihole.middlewares=pihole-https-redirect,"
      # - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.routers.pihole-secure.entrypoints=https"
      # - "traefik.http.routers.pihole-secure.rule=Host(${DNS_DOMAIN})"
      # - "traefik.http.routers.pihole-secure.tls=true"
      # - "traefik.http.routers.pihole-secure.tls.certresolver=http"
      # - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"


networks:
  proxy:
    external: true
